### PR TITLE
Make schema updates work on non-Windows platforms

### LINKED ISSUE #131: Schema update process only runs on Windows
### Description
Running the schema update process with `mvn clean install -P process-schemas` on a Unix-like platform results in the following exception:

```
Caused by: java.lang.IllegalArgumentException: /home/magnusbk/src/eiffel-remrem-semantics/src\main\resources\schemas\input does not exist
    at org.apache.commons.io.FileUtils.verifiedListFiles (FileUtils.java:1741)
    at org.apache.commons.io.FileUtils.cleanDirectory (FileUtils.java:1716)
    at com.ericsson.eiffel.remrem.semantics.schemas.LocalRepo.readSchemas (LocalRepo.java:46)
    at com.ericsson.eiffel.remrem.semantics.clone.PrepareLocalEiffelSchemas.main (PrepareLocalEiffelSchemas.java:194)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run (ExecJavaMojo.java:294)
    at java.lang.Thread.run (Thread.java:748)
```

This is unsurprising given the backslash-separated paths in [EiffelConstants](https://github.com/eiffel-community/eiffel-remrem-semantics/blob/07d8ab4f7bcaf6810edc316b990a0337cc81806e/src/main/java/com/ericsson/eiffel/remrem/semantics/schemas/EiffelConstants.java).

### Motivation
The schema update process should obviously be possible to run on platforms other than Windows.

### Exemplification
I'd like to be able to update the schemas from a Linux host.

### Benefits
Obvious.

### Possible Drawbacks
None.

### PR DESCRIPTION
**Pull request by magnusbaeck**
### Applicable Issues
Closes #131 

### Description of the Change
Fixes two fatal problems encountered while trying to update schemas and generate POJOs on Linux:

* Removes backslashes from pathnames.  Reworks various constants in EiffelConstants to be java.nio.file.Path    objects instead of strings. That makes the intention of the constants    clear and we can easily work with Path objects to generate correct    paths on any platform.
* Makes schema generation independent of order of files returned from OS.    Previously all versions of the events were returned and they were all    converted and written to the same destination file. This happened to    work fine when the list of files returned from File.listFiles()    was in the correct order so that the latest version was the last file    to be processed. If that wasn't the case one or more schema files    didn't get the most recent version of the event.    We address this by using a version string parser to sort the filenames    in version order before picking the greatest version and generating a    schema from that file only.

### Alternate Designs
None.

### Benefits
Non-Windows users can update the schemas.

### Possible Drawbacks
None.

### Sign-off

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I    have the right to submit it under the open source license    indicated in the file; or

(b) The contribution is based upon previous work that, to the best    of my knowledge, is covered under an appropriate open source    license and I have the right under that license to submit that    work with modifications, whether created in whole or in part    by me, under the same open source license (unless I am    permitted to submit under a different license), as indicated    in the file; or

(c) The contribution was provided directly to me by some other    person who certified (a), (b) or (c) and I have not modified    it.

(d) I understand and agree that this project and the contribution    are public and that a record of the contribution (including all    personal information I submit with it, including my sign-off) is    maintained indefinitely and may be redistributed consistent with    this project or the open source license(s) involved.

Signed-off-by: Magnus Bäck \<magnus.back@axis.com\>

### CODE REVIEW

**Review by SantoshNC68 — APPROVED** [review]

**Review by raja-maragani — APPROVED** [review]
Nice code refactor changes.

**Comment by m-linner-ericsson** [comment]
@raja-maragani @SantoshNC68: Should we merge this now or do we have anything outstanding?

**Comment by SantoshNC68** [comment]
We have a small task to change the domain Id part of handling, once that is done we can merge this changes
We will complete that task soon.

**Comment by magnusbaeck** [comment]
> We have a small task to change the domain Id part of handling, once that is done we can merge this changes
We will complete that task soon.

How does the domain id code overlap with this patch?

**Comment by SantoshNC68** [comment]
sorry thought this was the paris release, the other PR. my mistake. It is ok to merge this change.

**Comment by SantoshNC68** [comment]
I will merge these changes

**Review by SantoshNC68 — APPROVED** [review]

**Comment by SantoshNC68** [comment]
Will make a release of this along with the domain Id changes.

**Comment by magnusbaeck** [comment]
Thanks! I'm just about to push the PR for reverting manual changes which would enable merging the Paris update. Including those two PRs in the new release would probably save everyone's time.

**Pull request merged**
